[package]
name = "async-os"
version = "0.1.0"
edition = "2021"

[dependencies]
buddy_system_allocator = "0.6.0"
sbi-rt = "0.0.3"
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] }
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
